# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA.xci
# IP: The module: 'clk_VGA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_VGA'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: G:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA.xci
# IP: The module: 'clk_VGA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/2019fall_digital_design_project/VGA2.srcs/sources_1/ip/clk_VGA/clk_VGA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
